Repository aturingmachine/hockey-elo-tracker, pull requests merged in 2019-01, with the labels that each got.

#16 Add setup doc and add link to it in readme
  .github/README.MD
  docs/dev-support/setup.md
Labels: documentation

#14 Issue-8: Enhancement - Create Elo calculator class
  .gitignore
  PULL_REQUEST_TEMPLATE.md
  server/src/main/kotlin/com/hockey/elo/elotracker/EloTrackerApplication.kt
  server/src/main/kotlin/com/hockey/elo/elotracker/elohistory/controller/EloHistoryController.kt
  server/src/main/kotlin/com/hockey/elo/elotracker/elohistory/model/EloHistoryRecord.kt
  server/src/main/kotlin/com/hockey/elo/elotracker/elohistory/repository/EloHistoryRepository.kt
  server/src/main/kotlin/com/hockey/elo/elotracker/elohistory/service/EloHistoryService.kt
  server/src/main/kotlin/com/hockey/elo/elotracker/match/controller/MatchController.kt
  server/src/main/kotlin/com/hockey/elo/elotracker/match/exception/MatchNotFound.kt
  server/src/main/kotlin/com/hockey/elo/elotracker/match/model/MatchCreationRequest.kt
  server/src/main/kotlin/com/hockey/elo/elotracker/match/model/MatchDTO.kt
  server/src/main/kotlin/com/hockey/elo/elotracker/match/model/MatchRecord.kt
  server/src/main/kotlin/com/hockey/elo/elotracker/match/model/MatchUpdateRequest.kt
  server/src/main/kotlin/com/hockey/elo/elotracker/match/repository/MatchRepository.kt
  server/src/main/kotlin/com/hockey/elo/elotracker/match/service/MatchService.kt
  server/src/main/kotlin/com/hockey/elo/elotracker/statistics/EloRatings.kt
  server/src/main/kotlin/com/hockey/elo/elotracker/user/controller/UserController.kt
  server/src/main/kotlin/com/hockey/elo/elotracker/user/exception/UserAlreadyRegistered.kt
  server/src/main/kotlin/com/hockey/elo/elotracker/user/exception/UserNotFound.kt
  server/src/main/kotlin/com/hockey/elo/elotracker/user/model/UserDTO.kt
  server/src/main/kotlin/com/hockey/elo/elotracker/user/model/UserLoginSubmission.kt
  server/src/main/kotlin/com/hockey/elo/elotracker/user/model/UserRecord.kt
  server/src/main/kotlin/com/hockey/elo/elotracker/user/repository/UserRepository.kt
  server/src/main/kotlin/com/hockey/elo/elotracker/user/service/UserService.kt
  server/src/main/resources/application.properties
  server/src/test/kotlin/com/hockey/elo/elotracker/EloTrackerApplicationTests.kt
  server/src/test/kotlin/com/hockey/elo/elotracker/statistics/EloRatingsTest.kt
Labels: enhancement

#20 #18 start web app
  server/src/main/elo-tracker-web/.gitignore
  server/src/main/elo-tracker-web/README.md
  server/src/main/elo-tracker-web/babel.config.js
  server/src/main/elo-tracker-web/package-lock.json
  server/src/main/elo-tracker-web/package.json
  server/src/main/elo-tracker-web/public/favicon.ico
  server/src/main/elo-tracker-web/public/index.html
  server/src/main/elo-tracker-web/src/App.vue
  server/src/main/elo-tracker-web/src/assets/.gitkeep
  server/src/main/elo-tracker-web/src/components/.gitkeep
  server/src/main/elo-tracker-web/src/main.js
  server/src/main/elo-tracker-web/src/plugins/vuetify.js
  server/src/main/elo-tracker-web/src/services/.gitkeep
Labels: enhancement

#22 Move PULL_REQUEST_TEMPLATE to .github
  .github/PULL_REQUEST_TEMPLATE.md
Labels: chore, documentation

#27 Issue #19: Add Test Data SQL file
  server/src/main/kotlin/com/hockey/elo/elotracker/elohistory/repository/EloHistoryRepository.kt
  server/src/main/kotlin/com/hockey/elo/elotracker/elohistory/service/EloHistoryService.kt
  server/src/main/resources/application.properties
  server/src/main/resources/data.sql
Labels: chore, enhancement

#35 ELO-4: Complete Match CRUD Operations
  server/src/main/kotlin/com/hockey/elo/elotracker/match/controller/MatchController.kt
  server/src/main/kotlin/com/hockey/elo/elotracker/match/service/MatchService.kt
Labels: enhancement

#32 Add basic users table view to the web app
  server/src/main/elo-tracker-web/package-lock.json
  server/src/main/elo-tracker-web/package.json
  server/src/main/elo-tracker-web/src/App.vue
  server/src/main/elo-tracker-web/src/config/http.js
  server/src/main/elo-tracker-web/src/main.js
  server/src/main/elo-tracker-web/src/router.js
  server/src/main/elo-tracker-web/src/services/.gitkeep
  server/src/main/elo-tracker-web/src/views/Users.vue
  server/src/main/kotlin/com/hockey/elo/elotracker/user/controller/UserController.kt
  server/src/main/resources/application.properties
Labels: enhancement

#43 Add Issue Template and Contributing Guide
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE.md
  .github/README.MD
Labels: documentation

#45 ELO-37,38,39,42: Enhancement - Separates GameType from User
  server/src/main/kotlin/com/hockey/elo/elotracker/elohistory/controller/EloHistoryController.kt
  server/src/main/kotlin/com/hockey/elo/elotracker/elohistory/model/EloHistoryDTO.kt
  server/src/main/kotlin/com/hockey/elo/elotracker/elohistory/model/EloHistoryRecord.kt
  server/src/main/kotlin/com/hockey/elo/elotracker/elohistory/repository/EloHistoryRepository.kt
  server/src/main/kotlin/com/hockey/elo/elotracker/elohistory/repository/models/EloHistoryRecord.kt
  server/src/main/kotlin/com/hockey/elo/elotracker/elohistory/service/EloHistoryService.kt
  server/src/main/kotlin/com/hockey/elo/elotracker/match/controller/MatchController.kt
  server/src/main/kotlin/com/hockey/elo/elotracker/match/model/MatchCreationRequest.kt
  server/src/main/kotlin/com/hockey/elo/elotracker/match/model/MatchDTO.kt
  server/src/main/kotlin/com/hockey/elo/elotracker/match/model/MatchRecord.kt
  server/src/main/kotlin/com/hockey/elo/elotracker/match/model/MatchSummaryDTO.kt
  server/src/main/kotlin/com/hockey/elo/elotracker/match/model/ScoreUpdateRequest.kt
  server/src/main/kotlin/com/hockey/elo/elotracker/match/model/UserMatchStatsDTO.kt
  server/src/main/kotlin/com/hockey/elo/elotracker/match/repository/MatchRepository.kt
  server/src/main/kotlin/com/hockey/elo/elotracker/match/repository/models/MatchRecord.kt
  server/src/main/kotlin/com/hockey/elo/elotracker/match/service/MatchService.kt
  server/src/main/kotlin/com/hockey/elo/elotracker/shared/models/GameType.kt
  server/src/main/kotlin/com/hockey/elo/elotracker/user/controller/UserController.kt
  server/src/main/kotlin/com/hockey/elo/elotracker/user/model/UserDTO.kt
  server/src/main/kotlin/com/hockey/elo/elotracker/user/model/UserRecord.kt
  server/src/main/kotlin/com/hockey/elo/elotracker/user/model/UserStatsDTO.kt
  server/src/main/kotlin/com/hockey/elo/elotracker/user/repository/UserRepository.kt
  server/src/main/kotlin/com/hockey/elo/elotracker/user/repository/UserStatsRepository.kt
  server/src/main/kotlin/com/hockey/elo/elotracker/user/repository/models/UserRecord.kt
  server/src/main/kotlin/com/hockey/elo/elotracker/user/repository/models/UserStatsRecord.kt
  server/src/main/kotlin/com/hockey/elo/elotracker/user/service/UserService.kt
  server/src/main/resources/application.properties
  server/src/main/resources/data.sql
Labels: enhancement

#48 Create hardware configuration
  hardware configuration
Labels: documentation, hardware

#49 ELO-40: Enhancement - Update Match History to Support Mutiple Games
  hockeyEloTracker-ios/hockeyEloTracker.xcworkspace/xcuserdata/donjohnson.xcuserdatad/UserInterfaceState.xcuserstate
  server/src/main/kotlin/com/hockey/elo/elotracker/elohistory/controller/EloHistoryController.kt
  server/src/main/kotlin/com/hockey/elo/elotracker/elohistory/repository/EloHistoryRepository.kt
  server/src/main/kotlin/com/hockey/elo/elotracker/elohistory/service/EloHistoryService.kt
  server/src/main/kotlin/com/hockey/elo/elotracker/match/controller/MatchController.kt
Labels: enhancement

#51 ELO-50: Documentation: Go through EloTracker server docs and diagram and make sure they are updated
  .gitignore
  docs/data-models/data-models.md
  docs/dev-support/setup.md
  docs/kiosk-hardware/hardware-config.md
  docs/kiosk-hardware/operating-system-config.md
  docs/web-sequence-diagrams/Elo Tracker.png
  docs/web-sequence-diagrams/Elo Tracker.txt
  docs/web-sequence-diagrams/EloHistory GET _api_v1_users_{userId}_elo-history.png
  docs/web-sequence-diagrams/EloHistory GET _api_v1_users_{userId}_elo-history.txt
  docs/web-sequence-diagrams/Match GET _api_v1_matches_.png
  docs/web-sequence-diagrams/Match GET _api_v1_matches_.txt
  docs/web-sequence-diagrams/Match GET _api_v1_matches_{id}.png
  docs/web-sequence-diagrams/Match GET _api_v1_matches_{id}.txt
  docs/web-sequence-diagrams/Match POST _api_v1_matches.png
  docs/web-sequence-diagrams/Match POST _api_v1_matches.txt
  docs/web-sequence-diagrams/Match Put _api_v1_matches_{id}_score.png
  docs/web-sequence-diagrams/Match Put _api_v1_matches_{id}_score.txt
  docs/web-sequence-diagrams/Match Put _api_v1_matches_{id}_winner_{winnerId}.png
  docs/web-sequence-diagrams/Match Put _api_v1_matches_{id}_winner_{winnerId}.txt
  docs/web-sequence-diagrams/User Get _api_v1_users.png
  docs/web-sequence-diagrams/User Get _api_v1_users.txt
  docs/web-sequence-diagrams/User Get _api_v1_users_{id}.png
  docs/web-sequence-diagrams/User Get _api_v1_users_{id}.txt
  docs/web-sequence-diagrams/User Post _api_v1_users_.png
  docs/web-sequence-diagrams/User Post _api_v1_users_.txt
  server/src/main/kotlin/com/hockey/elo/elotracker/elohistory/controller/EloHistoryController.kt
  server/src/main/kotlin/com/hockey/elo/elotracker/elohistory/model/EloHistory.kt
  server/src/main/kotlin/com/hockey/elo/elotracker/elohistory/service/EloHistoryService.kt
  server/src/main/kotlin/com/hockey/elo/elotracker/match/controller/MatchController.kt
  server/src/main/kotlin/com/hockey/elo/elotracker/match/model/Match.kt
  server/src/main/kotlin/com/hockey/elo/elotracker/match/model/MatchSummary.kt
  server/src/main/kotlin/com/hockey/elo/elotracker/match/model/UserMatchStats.kt
  server/src/main/kotlin/com/hockey/elo/elotracker/match/service/MatchService.kt
  server/src/main/kotlin/com/hockey/elo/elotracker/user/controller/UserController.kt
  server/src/main/kotlin/com/hockey/elo/elotracker/user/model/User.kt
  server/src/main/kotlin/com/hockey/elo/elotracker/user/model/UserLoginRequest.kt
  server/src/main/kotlin/com/hockey/elo/elotracker/user/model/UserStats.kt
  server/src/main/kotlin/com/hockey/elo/elotracker/user/service/UserService.kt
  server/src/test/kotlin/com/hockey/elo/elotracker/elohistory/controller/EloHistoryControllerTest.kt
  server/src/test/kotlin/com/hockey/elo/elotracker/elohistory/service/EloHistoryServiceTest.kt
  server/src/test/kotlin/com/hockey/elo/elotracker/match/controller/MatchControllerTest.kt
  server/src/test/kotlin/com/hockey/elo/elotracker/match/service/MatchServiceTest.kt
  server/src/test/kotlin/com/hockey/elo/elotracker/user/controller/UserControllerTest.kt
  server/src/test/kotlin/com/hockey/elo/elotracker/user/service/UserServiceTest.kt
Labels: documentation
